### ISSUE TITLE
Add "offsets X tons of carbon" text slugs on home page, profile page - see code DM slacked

### ISSUE THREAD

**Issue by desmondmullen** [ralracish/goTreeUrself#71]

**Comment by timwelsh** [comment]
Whoever does this please clean up the way the text is viewed by increasing/decreasing or removing the text-shadow because the way it displays now looks very blurry to me.

**Comment by desmondmullen** [comment]
The text slugs and formatting are in place. I've increased the point size to address the blurriness issue that Tim saw. All we need is to plug in the numbers. On the profile page we're already getting the number of trees a user has so hopefully multiplying that by 4.3 tons will not be hard. Please let me know if you need help with this!

**Comment by desmondmullen** [comment]
done and merged
